### ISSUE TITLE
Cmake

### ISSUE THREAD

**Issue by 24332006** [daflad/ReebGraph#1]
Hello, may I ask why the source file Cone.cxx cannot be found when compiling the source code in Cmake, thanks!

**Comment by daflad** [comment]
Hi, it been 6 years since I worked on this but all the make files were generated by Xcode, how are you trying to build the project?

**Comment by 24332006** [comment]
> 嗨，距我从事此工作已有6年了，但是所有make文件都是由Xcode生成的，您如何尝试构建该项目？

I have less experience with this, please help me to see it, thank you!
![1](https://user-images.githubusercontent.com/56919744/77996426-28fdd580-7360-11ea-86f2-be4d5e97cb3d.png)
![2](https://user-images.githubusercontent.com/56919744/77996432-2b602f80-7360-11ea-8789-1f41db9a147d.png)
![3](https://user-images.githubusercontent.com/56919744/77996461-3a46e200-7360-11ea-96e9-9caeab8403c0.png)

**Comment by daflad** [comment]
I don't think you will be able to use this code on windows without modifying the build scripts.  All this cmake code was generated by Xcode (https://developer.apple.com/xcode/).

If you do not have access to OS X I suggest installing virtual machine with OS X then adding Xcode and OpenGL then it will have a chance to compile.

The file Cone.cxx is part of the OS X OpenGL lib.

I have never used windows for development so I am unlikely to know how to make it work.

**Comment by 24332006** [comment]
> I don't think you will be able to use this code on windows without modifying the build scripts. All this cmake code was generated by Xcode (https://developer.apple.com/xcode/).
> 
> If you do not have access to OS X I suggest installing virtual machine with OS X then adding Xcode and OpenGL then it will have a chance to compile.
> 
> The file Cone.cxx is part of the OS X OpenGL lib.
> 
> I have never used windows for development so I am unlikely to know how to make it work.

OK, thank you very much！
